= `AITExtActionTransport`

救急隊の行動を決定するためのモジュールです．

== フィールド

救助対象者のID::
`AITAmbulanceTeamDetector` で決定した救助対象者のIDを`setTarget` よりセットします．

搬送先の避難所のID::
避難所選択モジュールの計算結果をセットします．

== サブモジュール

経路探索モジュール::
救助対象者や避難所までの経路探索に利用します．

避難所選択モジュール::
搬送先の避難所の選択に利用します．

== コンストラクタ

* 救助対象者，搬送先の避難所，司令所から割り当てられた避難所のIDを `null` にセット
* 経路探索モジュールと避難所選択モジュールのロード

== `setTarget(EntityID)`

指定された救助対象者のIDをセットします．また，避難所選択モジュールにも，救助対象者のIDをセットします．

== `updateInfo(MessageManager)`

サブモジュールの情報を更新します． また，司令所から次に向かうべき避難所の情報を受信し，その情報を保持します．

== `calc()`

エージェントの状態に応じた行動を計算します． エージェントの状態は次の3つを想定しています．

=== 救助対象者を探索中である状態

この状態は救助対象者が `null` で，誰も搬送していないときにを指します．この状態では，なにもせず，探索処理に移行します．

=== 救助対象者の救助に向かっている状態

この状態は救助対象者がセットされ，その場所へ移動している状態を指します．救助対象者と同じ位置にいるか，そうでないかで以下のように分かれます．

* 救助対象者と同じ位置にいない場合
+
その場所への経路探索を実行します．その結果をもとに，救助対象者の位置へ向かうための `ActionMove` を結果にセットします ．

* 救助対象者と同じ位置にいる場合
+
次の処理を実行します．

** 自身の情報をもとに避難所選択モジュールにより搬送先の避難所を算出し，そのIDをフィールドにセット
** 司令所に救助対象者を搬入することを連絡
** その場所の救助対象者を搬入するために `ActionLoad` を結果にセット

=== 救助対象者を避難所に搬送している状態

この状態はエージェントが市民を搬入している状態を指します．
このとき，次の条件を満たす場合は市民を搬出します．

* 搬送中の市民が死亡した
* エージェントが避難所に到着した

搬出時には，次の処理を実行します．

* 搬出することを司令所に連絡
* 搬出のために `ActionUnload` を結果にセット

条件を満たしていない場合は避難所に移動中であるため，避難所までの経路を経路探索モジュールにより計算し，その結果をもとに避難所に向かうための `ActionMove` を結果にセットします．

=== 例外処理

いずれの状態にもない場合は例外として処理します．

また，次の条件を満たす場合も例外とします．

* 救助に向かっている状態または避難所に搬送している状態において，救助対象者が市民以外である場合
* 救助に向かっている状態において，救助対象者の位置が建物以外である場合

例外が発生した場合は `ActionRest` を結果にセットします．
このときエージェントはなにもおこないません．

== `getAction()`

`calc()` で計算したこのエージェントの行動を返します．
