= `AITFireBrigadeSearch`

消防隊の救出対象者を捜索するためのモジュールです．

== フィールド

捜索対象のエンティティID::
この消防隊が捜索対象とする建物のエンティティIDです．
`calc()`により算出されます．

探索範囲内の建物のエンティティID::
この消防隊の探索範囲内の建物のエンティティIDです．
`calc()`により算出されます．

ある建物と，その建物に埋没している可能性のある市民のエンティティID集合のマップ::
キーを建物のエンティティIDとし，値にその建物に埋没している可能性のある市民のエンティティIDをセットとして保持するマップです．
市民のヘルプが聞こえた際に，自身の知覚範囲内にあるすべての建物について，それぞれの建物のエンティティIDをキーとするセットにその市民のエンティティIDを追加します．
また，救助が完了した市民は，マップから削除されます．

探索済みの建物のエンティティIDのセット::
これまでにこの消防隊が到達した建物のエンティティIDを保持するセットです．

探索が遅れている建物のエンティティIDのセット::
この消防隊が探索した建物で，がれきなどにより到達できなかった捜索対象の建物のエンティティIDを格納するセットです．
このセットはこの消防隊に新たに探索範囲を割り当てられた際に削除されます．

探索が遅れている建物のエンティティIDのセット（削除しないもの）::
この消防隊が探索した建物で，瓦礫などで到達できなかった捜索対象の建物のエンティティIDを格納するセットです．
このセットはこの消防隊に新たに探索範囲を割り当てられた際に削除されません．

探索が遅れている建物の探索優先度を下げるためのペナルティ::
それぞれの建物の探索優先度を決定するために利用されます．
ある建物に到達できない状況を知覚するたびに，その建物に対してこのペナルティが与えられます．
ペナルティが与えられた建物は探索の優先度が下がり，後回しとなります．このペナルティは埋没している可能性のある市民の数から引くため，埋没している可能性のある市民何人分というような意味を持ちます．

探索が遅れている建物の探索優先度を上げるための係数::
それぞれの建物の探索優先度を決定するために利用されます．
この探索モジュールでは，時間の経過とともに到達できなかった建物についても再度探索しにいくようにしています．
この係数は1ステップ経過するごとにどの程度ペナルティが減少させるかを示すものです．
これにより，探索が遅れている建物の優先度を再度高い状態へ遷移させます．

探索が遅れている建物の探索優先度を調整するためのペナルティを管理するMap::
探索優先度を決定する際に利用されます．
keyに建物のエンティティID,valueにdouble型のペナルティを格納します．

直前のクラスタ::
探索範囲を拡張する際に利用されます．
直前に割り当てられたクラスタを保持します．

過去に探索したクラスタ::
探索範囲を拡張する際に利用されます．
過去に割り当てられたことのあるクラスタを保持します．


== サブモジュール

クラスタモジュール::
クラスタの計算に利用されます．

瓦礫で到達できないことを検出するモジュール::
探索が遅れているかどうかの判断に利用されます．

瓦礫で動けないことを検出するモジュール::
探索が遅れているかどうかの判断に利用されます．

== `getTarget()`

この消防隊の救出対象者のIDを返します．

== `calc()`

消防隊の救出対象者がいない場合に呼び出されます．
探索対象の建物を決定し，resultにその建物を設定します．
以下の建物を自身の探索候補に設定します．

. 自身の割り当てられている探索範囲の中で到達済みではない建物

. 探索が遅れている建物

この探索候補の中で最も優先度の高いものを探索対象として決定します．
なお，建物の優先度は以下の様になっています．各基準は上のものから判断し，同順である場合に次の基準による判断します．

. (potentialsに含まれている市民の人数 - 探索が遅れている建物の集合に含まれていることによるペナルティ)の計算結果が大きいもの
. 自身からその建物へのユークリッド距離が小さいもの

自身の割り当てられている探索範囲内の建物で，探索が遅延している建物の集合に含まれている建物以外が探索完了した場合，新たな探索範囲を得ます．

また，calcメソッドが呼び出されるたびに探索が遅れている建物のペナルティを減少させます．これによって，周期的に探索が遅れている建物の優先度が上昇し，探索をおこなうことができる様になります．

== `initCluster()`

探索範囲の初期値を割り当てます．

== `expandCluster()`

探索範囲の拡張の条件を満たした際に，新しい探索範囲を獲得します．

== `needToExpandCluster()`

探索範囲を拡張するかどうかを判断します．
自身の割り当てられている探索範囲内の建物で，探索が遅延している建物の集合に含まれている建物以外が探索完了した場合，trueを返します．