= `AITFireBrigadeDetector`

消防隊の救助対象者を決定するためのモジュールです．

== フィールド

救出対象者のエンティティID::
この消防隊が救出対象とするエージェントのエンティティIDです．現在のエージェントが持つ知識からは，対象者を決定できない場合は `null` がセットされます．また，この場合に消防隊は `AITFireBrigadeSearch` により市民を探索します．

1人の対象を救出するときの消防隊の最大数::
1人の対象を救出するときの消防隊の最大数です．消防隊がある市民の救出に向かうかどうかの判定に使用します．このパラメータは経験的に決定するものとします．

== サブモジュール

経路探索モジュール::
エージェントの生存時間の予測，救出対象者まで経路距離の計算に利用します．

== `getTarget()`

この消防隊の救出対象者のIDを返します．

== `updateInfo(MessageManager)`

現状，通信メッセージから更新する知識がないため，親クラスの処理の呼び出しのみをおこないます．

== `calc()`

救出対象者を決定して，「救出対象者のID」をセットします．

この救出対象者の選択アルゴリズムでは，同じ建物のなかで複数のエージェントが埋没しているときを考慮します．通常複数のエージェントが埋没しているとき互いにどの救助部隊がどのエージェントを救出しているかが不明となります．このアルゴリズムでは，それを決定的なものとするために次のルールに従うこととします．

- 救出対象が優先度において同一の条件をもつとき，IDの小さいものを優先
- 同一の対象に必要数を超える複数の救助部隊が従事できるとき，IDの小さいものから従事し，自身のIDが大きいものはほかの対象の探索へ移行

また，救出の優先順は次のようになっています．各基準は上のものから判断し，同順である場合に次の基準による判断します．

a. エージェントの種類
+
救助全体への影響の大きい消防隊，土木隊，救急隊，市民の順にエージェントを救出します．

b. 経路距離
+
自身から対象が埋没している建物までの経路距離の近い順に救出します．

c. 埋没度
+
同じ建物に複数のエージェントがいる場合には，埋没度の小さい，確実に救出できるものから救出します．

d. エージェントID
+
埋没度までがすべて同じ値である場合，エージェントIDの小さいものを対象とします．

=== 1. 救出対象の候補の算出

次の条件をすべて満たすエージェントを救出対象とする．

a. 消防隊，救急隊，土木隊，市民のいずれかであること
b. 生存していること
c. 埋没していること
d. 救出に従事するエージェントが不足していること
e. 救助が間に合うこと

ここで，候補が存在しない場合は救出対象に `null` をセットして，探索へ移行します．

==== 救出に従事するエージェントが不足していること

「救出に従事するエージェントが不足していること」とは，この消防隊からみて，対象のエージェントに対する消防隊の数が「1人の対象を救出するときの消防隊の最大数」を超えていないことを指します．ただ，ここでは単純に数を比較するのでなく，自身がその対象を担当すべきかどうかを判断することとします．

また，対象の位置に，すでに救出にあたっている消防隊およびほかの救出対象がいる場合には，それぞれの消防隊がどの救出対象を救出しているかを考慮します．この情報は救出の優先度と消防隊のIDから算出します．

加えて，すでに救出にあたっている消防隊がいる場合に，自身が現場へ到着するまでに救出が完了する場合があります．こうした場合は救出活動への参加が不要であると判断し，対象から外します．

==== 救助が間に合うこと

「救助が間に合う」とは対象とするエージェントの救助にかかる時間を概算し，その間にエージェントが死亡しないことを指します．救助時間は対象が救助部隊の場合は救出完了するまで，市民の場合は救出後に最寄りの避難所へ搬送するまでの時間を考慮します．具体的には以下の式で算出します．

\[
\begin{array}{rl}
t_{total}     &= t_{travel} + t_{rescue} + t_{transport} \\
t_{travel}    &= TravelTime(p_{self}, p_{target}) \\
t_{resuce}    &= (b - n \cdot t_{travel}) / n_{max} \\
t_{transport} &= \begin{cases}
  TravelTime(p_{target}, p_{refuge}) & \text{if target is civilian} \\
  0 & \text{if target is rescue agent}
\end{cases}
\end{array}
\]

ここで，\(t_{total}\)は合計時間を表し，対象の位置までの移動時間 \( t_{travel}\)，救出にかかる時間 \( t_{rescue} \)，最寄りの避難所までの搬送時間 \(t_{transport}\)の和としています．

\( t_{travel}\)は自身の位置\( p_{self} \)から対象の位置\(p_{target}\)までの移動にかかる時間として算出します．

\( t_{rescue} \)は対象の埋没度が0になるまでの時間です．すでに現場に\(n\)人の消防隊がいるとした場合，到着したときには対象の埋没度は計算した時刻の埋没度より小さくなります．\( t_{rescue} \)の算出における分子はこれを考慮するものです．また，\( t_{rescue} \)は対象に対して消防隊が最大数割り当たったときの時間にしています．これは「救助が間に合うこと」という条件を緩和するものです．特に現場に消防隊がいない場合にこの\( t_{rescue} \)が大きくなりすぎるのを防いでいます．ここでは，将来的に現場で活動する消防隊が最大まで増えることを期待しています．

\( t_{transport} \)は対象の搬送にかかる時間です．対象が救助部隊である場合は搬送する必要がないため，\( t_{transport} = 0 \)としています．市民の場合は最寄りの避難所までの時間を計算します．

=== 2. 救出の継続判断

救出対象の候補に現在の救出対象が含まれている場合はそのエージェントのIDを救出対象にセットして，終了します．そうでない場合は次の手順から，新しい救出対象を決定します．

=== 3. 優先順位から対象を選択

優先順位に従い，候補から最も優先すべき対象を選択します．
