= `RefugeSelector`
:stem:

避難所を選択するためのモジュールです．

== フィールド

各避難所の情報::
エージェントの知覚から更新します．

救助対象者のID::
`setTarget(EntityID)` でセットされます．

選択された避難所のID::
結果として選択された避難所のIDをセットします．

乱数生成器::
避難所の選択で利用する乱数生成器をセットします．

== サブモジュール

経路探索モジュール::
避難所の選択において，救助対象者から避難所までの経路長を考慮するために，その経路計算に使用します．

== `RefugeInfo`

避難所の情報を保持するためのデータ構造です．以下の情報を要素として持ちます．

* ベッドの数
* 避難所にいる市民の負傷度

また，以下の要素を計算により提供します．

* 避難所にいる市民の平均ダメージ
* 避難所にいる市民の合計ダメージ
* 市民の数

== コンストラクタ

* 避難所の情報，救助対象者の情報，選択先の避難所を初期化
* `develop.json` より読み込んだ乱数シードをもとにした乱数生成器の作成
* 経路探索モジュールのロード

== `updateInfo(MessageManager)`

エージェントの知覚情報から，避難所の情報とそこにいる市民の情報を更新します．

== `setTarget(EntityID)`

救助対象者のIDをセットします．

== `calc()`

=== 全体の流れ

避難所選択全体は次の手順で実行します．それぞれの詳細を次に述べていきます．

1. 各避難所に搬送する場合に救助対象者が治療を受けられるまでの時間を算出
2. 救助対象者の生存時間内に生存できる場合は搬送先の候補とし，そうでない場合は候補から除外
3. 候補の避難所から，1. で算出した時間の長さを適応度としてルーレット選択により搬送先を確率的に決定

=== 避難所の選択確率

救助対象者の搬送先に相応しい避難所を計算し，選択します．ここでは各避難所の選択確率を求め，避難所を選択することとします．避難所 \( r_i \) を選択する確率 \(P(\theta)\) を次のように定義します．

\[ P(\theta = r_i) = \frac{ t_i^{-1} }{\sum{ t_i^{-1} }}\]

* \( r_i \in R \): \( i \) 番目の避難所
* \( t_i \): \( i \) 番目の避難所に搬送した場合に，救助対象者の治療開始までにかかる時間

避難所へ搬送後より早く治療を開始できる方が，市民を生存させられる可能性が高く望ましいです．そのため，各避難所までの時間の逆比をとることで時間のかからない避難所がより高い確率で選択されるようにしています．

=== 治療開始までの時間

ある避難所へ搬送した場合に，救助対象者の治療開始までにかかる時間の算出では，移動にかかる時間 \( TravelingTime \)と病床が利用可能になるまでの待ち時間 \(WaitingTime\) を考慮する必要があります．ここで， \( t_i \) を次のように定義します．

\[ t_i = Max(TravelingTime, WaitingTime) \]

\( TravelingTime > WaitingTime \) の場合，到着時には病床が利用可能です．一方で\( TravelingTime < WaitingTime \) の場合，移動時間と病床が利用可能になるまでの待ち時間を総合して待つ時間は \( WaitingTime \) に等しくなります．

=== 避難所までの移動時間

避難所までの移動時間は避難所までの経路距離とエージェントの移動速度から，次の式で求まります．

\[ TravelingTime = \frac{ PathLength }{ AgentSpeed } \]

* \( PathLength \): 避難所 \( i \) までの経路距離（経路探索モジュールにより算出）
* \( AgentSpeed \): エージェントの移動速度（ `develop.json` にパラメータとして設定 ）

エージェントの移動速度は事前実験から求めておき， `develop.json` に定数として登録しておきます．

=== 病床が利用可能になるまでの時間

病床が利用可能になるまでの時間\( WaitingTime \)はErlangの待ち行列モデル（M/M/C）により計算します．待ち行列モデルにはさまざまなものがありますが，このモデルでは，RoboCupRescueの避難所のように1つの行列に対して，複数のサーバ（病床）がある場合を考慮するものです．

Erlangの待ち行列モデル（M/M/Cモデル）において行列の平均待ち時間 \( W \) は次式で求まることが知られています．

\[
W = \pi_0 \frac{ \rho (c \rho)^c }{ \lambda (1 - \rho)^2 c! }
\]

* \( c \): サービス数
* \( \lambda \): 平均到着率
* \( \rho \): 利用率
* \( \pi_0 \): 定常過程において顧客数が0となる確率

ここで，避難所では病床数の数 \( BedCapacity \) だけ，負傷した市民に対応できるため，サービス数 \( c \) は

\[ c = BedCapacity \]

とできます．また，ここでは平均到着率 \( \lambda \) は1ステップに何人の市民が避難所に搬送されてくるかを示します．これはエージェントの観測から直接得られないため，事前実験で調査した値を `develop.json` を経由して得ることとします．

次に，利用率 \( \rho \) は

\[
\rho = \frac{ \lambda }{ \mu }
\]

で定義される統計量です．ここで用いられる \( \mu \) は平均サービス率（離脱率）で，ここでは避難所が単位時間に治療を終えられる人数になります．つまり，利用率は行列から1人離脱するときに，何人が到着するかを示します．

避難所では，1ステップに市民のダメージを1だけ回復させられることから，1ステップで対処できる人数は1以下の値となります．平均サービス率 \( \mu \) は過去の観測から次のようにして計算することとします．

\[ \mu = \frac{ 1 }{ AverageDamage } \]

\( AverageDamage \) は対象とする避難所にいた市民のダメージの平均値を示します．各病床ではその市民の治療にダメージ分の時間がかかるため，1ステップで治療を終えられる人数はその逆数となります．市民によりダメージの量は異なるため，治療に要する時間も異なりますが，ダメージの平均値を治療の平均所要時間として計算します．

次に，顧客数が0となる確率 \( \pi_0 \) は次のように計算できることが知られています．

\[
\pi_0 =
\left[
\left(
  \sum^{ c-1 }_{ k=0 }\frac{ ( c\rho )^k }{ k! }
\right)+
\frac{ ( c\rho )^c }{ c! }
\frac{ 1 }{ 1 - \rho }
\right]^{ -1 } \]

このように \( \pi_0 \) はサービス数，平均到着率，利用率から求められます．

以上を避難所における待ち時間として計算します．なお，対象の避難所を観測していない場合は避難所の市民の情報がなく，計算ができません．その場合は待ち時間が0となるため，経路距離のみから選択確率が求められます．

=== 例外処理

救助対象者が指定されていない場合は結果に `null` をセットして計算を終了します．

== `getResult()`

選択された避難所のIDを返します．
なお，次の場合には `getResult()` は `null` を返します．

* すべての避難所について生存時間内に搬送できないという場合
* 救助対象者が指定されていない場合
